{% set name = "deepgraph" %}
{% set version = "1.0.0" %}
{% set sha256 = "d0b49f9bd553eeaf31d6d063bcbed122b77e0c85f018aa6b3ee3be689c20537c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - wheel
    - setuptools >=61.0
    - numpy >=2.0.0
    - cython >3
    - pip
  run:
    - python
    - pandas >=1.2

test:
  imports:
    - deepgraph

about:
  home: https://github.com/deepgraph/deepgraph
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  license_url: https://github.com/deepgraph/deepgraph/blob/master/LICENSE
  summary: Analyze Data with Pandas-based Networks.
  description: |
    DeepGraph is a scalable, general-purpose data analysis package. It
    implements a network representation based on pandas DataFrames and
    provides methods to construct, partition and plot graphs, to interface
    with popular network packages and more.
  dev_url: https://deepgraph.readthedocs.io/en/latest/installation.html#installation-from-source-environment-setup
  doc_url: https://deepgraph.readthedocs.io/
  doc_source_url: https://github.com/deepgraph/deepgraph/blob/master/README.rst

extra:
  recipe-maintainers:
    - dominiktraxl
