{% set name = "DeepGraph" %}
{% set version = "0.2.1" %}
{% set sha256 = "4e7d69c2c03d94647a03e35f7e1a927a1d489a1e47590f4285e2e5bdbd5a608a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py33]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - toolchain
  run:
    - python
    - numpy x.x
    - pandas

test:
  imports:
    - deepgraph

about:
  home: https://github.com/deepgraph/deepgraph
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Analyze Data with Pandas-based Networks.'
  description: |
    DeepGraph is a scalable, general-purpose data analysis package. It
    implements a network representation based on pandas DataFrames and
    provides methods to construct, partition and plot graphs, to interface
    with popular network packages and more.
  doc_url: https://deepgraph.readthedocs.io/

extra:
  recipe-maintainers:
    - dominiktraxl
