{% set name = "DeepGraph" %}
{% set version = "0.2.3" %}
{% set sha256 = "67a5483c7763822fa20e0f815e321a6cc5bb9b48d0755f1154fd28bbfd36ca26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  script:
    - cythonize deepgraph/*.pyx  # [py>36]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas

test:
  imports:
    - deepgraph

about:
  home: https://github.com/deepgraph/deepgraph
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Analyze Data with Pandas-based Networks.
  description: |
    DeepGraph is a scalable, general-purpose data analysis package. It
    implements a network representation based on pandas DataFrames and
    provides methods to construct, partition and plot graphs, to interface
    with popular network packages and more.
  doc_url: https://deepgraph.readthedocs.io/

extra:
  recipe-maintainers:
    - dominiktraxl
