# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=112  CONDA_PY=27
    - CONDA_NPY=113  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=35
    - CONDA_NPY=112  CONDA_PY=35
    - CONDA_NPY=113  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=36
    - CONDA_NPY=112  CONDA_PY=36
    - CONDA_NPY=113  CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "xo1JvqIuxxmn5P5y4jwIl5dxFherUHxRC8Md8iL1IzD0h0STu6WFBVv1nUor3u84sJM+rEDxvlt99hmNTTCHXulxfxPI7SHnY2N6bAoRAm3A2duJe5RM6k02aVj+M2IQNMU1V5AtA9ZQx6g89IdEib1pJmHwqsip+oW/8NcFs4mkzjzy18oDx33jWTLq28oddSjSbnzhIcyRgo32FC5YWZI3YgraXlVnBEbUpWZYooCi8nod4GRpw0RXUXpoAO9+APn7504R63I9XsUUBfEB0YT2RcJ+l/h5jgINA5SfV3Ji5B5L+a+tuJ9jzkwxihtBwZZIlY7aKO5mZNNODlVdfS7Zf5VYf5O+FKW2XTnv+niN2XpCCgljjmgcZePG4xH2SW1yrgeLf2Y/oAebtmv7beMzoTbUKljFRkyaDicnJjD0ZOcjJpf78WCD9r+YEltB/pPFEHsI1UWrvxUKne8NmyTnU/p2wlDEb0qTrNaQIGQDwl49KeIq5HUnEkyGfZrb9osTxc5AfY58lejigYfddVsPGCNAgFrDlN2Xot1TAY5j8hME2UUAd/67NTOqA/Exh77F5eUpoRG0gX7tyRlmNLDUdMFPyd5QPnFV4OUG8rEJMZ1XvfYP8deVfKRhdzRCDBtkoDhNL3n2Kf4veczN//Jg8BAwpNjM8fEinRc11Hk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
