travis:
  secure:
    BINSTAR_TOKEN: 3tjo/2bmkB+UehE2y4Sz/EpsMDt4ZQGI3MP9ZoVQmaMrwFjgdtzfhYhZ+04bqJoB3/Mj1D11y572SqxRErt1ba7yLKiCvNc5/7P/KApOHZsLZR+6xhwrTu8FPajb99LLVe2YZi12ytzvfpGv5DFlj0yU3RSo8R6aDN+0aImt4CYvvzTeCFSTecCH5P4cPCmm9sPCimQ7T5b7/tAyEdQbC2MTsbjWXXaUFEvHeZzev66a8lrO3l+xgnw4m7GROeXjcCPzfqg/q9y7PTN66S8avTqpl/W2abDSP63zezYhTzbzVVLIRhxAD49+yJ1X0qY1v0g/goQaCl+LOil2IbWEe1LaynoLxSjV+zAK1zpxJkmwspnaerYnTs0Auz1sHNBbd7oL5iCwSRb7LkYsf4AazcqVurGpBbwS52ERW4BWojFNZeLu16FOtSivdfskOtHZrTJy3qPtoePnpiWX9Q+hB5K0rM6YUUoYN78rU0XjQNDZI14PnWshJ2NGkVl5g/JPdBnp+hyqGa9WVLLRfnAFaw61CHeR0ANocutfn+363o2TjdN1oBca0gO1Hcoim7Fv4TL3TQpYeUW4Gi3fFk+jTVKOcQ74rZ8FZq5mAOz0R4Ja7O/+V+r/0AEw83OmoaYQjLTvgKNx+s34cfTaPR5PyihezABkNTUrVHKmRuLt6oI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
