travis:
  secure:
    BINSTAR_TOKEN: xo1JvqIuxxmn5P5y4jwIl5dxFherUHxRC8Md8iL1IzD0h0STu6WFBVv1nUor3u84sJM+rEDxvlt99hmNTTCHXulxfxPI7SHnY2N6bAoRAm3A2duJe5RM6k02aVj+M2IQNMU1V5AtA9ZQx6g89IdEib1pJmHwqsip+oW/8NcFs4mkzjzy18oDx33jWTLq28oddSjSbnzhIcyRgo32FC5YWZI3YgraXlVnBEbUpWZYooCi8nod4GRpw0RXUXpoAO9+APn7504R63I9XsUUBfEB0YT2RcJ+l/h5jgINA5SfV3Ji5B5L+a+tuJ9jzkwxihtBwZZIlY7aKO5mZNNODlVdfS7Zf5VYf5O+FKW2XTnv+niN2XpCCgljjmgcZePG4xH2SW1yrgeLf2Y/oAebtmv7beMzoTbUKljFRkyaDicnJjD0ZOcjJpf78WCD9r+YEltB/pPFEHsI1UWrvxUKne8NmyTnU/p2wlDEb0qTrNaQIGQDwl49KeIq5HUnEkyGfZrb9osTxc5AfY58lejigYfddVsPGCNAgFrDlN2Xot1TAY5j8hME2UUAd/67NTOqA/Exh77F5eUpoRG0gX7tyRlmNLDUdMFPyd5QPnFV4OUG8rEJMZ1XvfYP8deVfKRhdzRCDBtkoDhNL3n2Kf4veczN//Jg8BAwpNjM8fEinRc11Hk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
