appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: A+1qCagPlpS/xa8FwHibs6FR/LoDPfomvZM/ypuI9o5aY3c7oBlu45FKL6LMgXTISmpKBPMO9+7vex30m0JBgC6Uc4AJZDfe75bcY4ofeOujBLrceLIZIeW4/V4xKmjocEqKTG889Eq6fB1OgjyZrM/XftPL1haLRlywJr0LGFxMq3LXoeqe4uPE4HcLmK72iH8oH/j9WZa/sf7aHbzCVCedLI4HihGF0TTz6MEruZf//yn6inpMvWsVxyIqJNeHAqWeKYYn5CFD0mxRNRkXtTgrTmpszhxqEKScjFj5FjdxvUzR9QPWG8GPxu+uwKEQk4apnfAQr7E3nlFuQAnuWECM6NFeHBVOcECiz4fGlogu3JaeM94kCBIi6o14+Y3qbvjrgzz2HpS5rXWp9GX2j7/TS6qYe4/Z3N/Tx2uc/f+KiYE3BbGhmmEC2VauuPctbCfiZFbXtlWvxuSQSy9oBGDShXoWwnzSVhglleDlmU/gtxg+1jqec604OUMaom+GGdajljxbpRRXcAsITSmo1oYMOtuBrnHVUOcTG6+uQxLluBi1QIZwwfCB7BGtci4JkAA8xCZi8pZtcIAe7oN0eTP2PNN/Y2sLMSI64qwozGkjbr06wgLgbZq4HjZJ1WM8+N1g08piaa6n+zyFPeWx2PjzcTv7uMQNn0cZqKyyxVo=}
